### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by rcon420** [1Mack/CS2-CallAdmin#1]
Could u make database stuff optional? I really don't see the point of storing calladmins in database just waste of space 
And could u add option to write your own reason?

**Comment by 1Mack** [comment]
Im using the database so you have log (can see exactly the admins who are really working on your server) and to use !report_handled (I grab the message_id from database)
If you really don't want it, there is another option, check this: https://github.com/PhantomYopta/-Discord-cs2-ReportSystem

About the custom reason, I can do it, that's a good option. I'll release a new version containg it soon.

**Comment by funcgoof** [comment]
> Im using the database so you have log (can see exactly the admins who are really working on your server) and to use !report_handled (I grab the message_id from database) If you really don't want it, there is another option, check this: https://github.com/PhantomYopta/-Discord-cs2-ReportSystem
> 
> About the custom reason, I can do it, that's a good option. I'll release a new version containg it soon.

Great! Would be nice as well if u could set that as only option. 

 just my personal experience giving only option for custom reason makes the reports from players more quality and insightful.

**Comment by 1Mack** [comment]
@rcon420 @funcgoof  In the new version has the option to not use Database and for custom reason.

**Comment by 1Mack** [comment]
https://github.com/1Mack/CS2-CallAdmin/releases/tag/V1.4
