### ISSUE TITLE
SSL Authentication Error

### ISSUE THREAD

**Issue by NotJustin** [1Mack/CS2-CallAdmin#2]
I was receiving an SSL Authentication Error when the plugin tried creating the database table.
I added to the MySqlConnectionStringBuilder SslMode = MySqlSslMode.None so it looks like this:

```
    var builder = new MySqlConnectionStringBuilder
    {
      Server = Config.Database.Host,
      UserID = Config.Database.User,
      Password = Config.Database.Password,
      Database = Config.Database.Name,
      Port = (uint)Config.Database.Port,
      ConvertZeroDateTime = true,
      SslMode = MySqlSslMode.None
    };
```

the table successfully created.

**Comment by 1Mack** [comment]
In the new version i've changed the SslMode to "preferred", so SSL will be used if the server supports it.

Can you test it ?


https://github.com/1Mack/CS2-CallAdmin/releases/tag/V1.4

**Comment by NotJustin** [comment]
I don't have much understanding of what it means to use SSL or not, but 1.4 resulted in same error.
After building 1.4 with SslMode "None" instead, error is gone.

**Comment by 1Mack** [comment]
hmm I'll add an option on Config, so you can choose to enable SSL or not
