### ISSUE TITLE
Lang pl

### ISSUE THREAD

**Issue by szogun1910** [1Mack/CS2-CallAdmin#5]
```
{
  "Prefix": "[{green}CallAdmin{default}]",
  "MissingCommandPermission": "{red}Nie masz uprawnień do użycia tego polecenia!",
  "NoPlayersAvailable": "Nie ma dostępnych graczy",
  "InCoolDown": "Trwa czas odnowienia... poczekaj {0} sekund i spróbuj ponownie",
  "ReportSent": "Twój raport został wysłany do administratorów!",
  "WebhookError": "Wystąpił błąd podczas wysyłania webhooka",
  "InsertIntoDatabaseError": "Wystąpił błąd podczas wstawiania do bazy danych!",
  "ReportNotFound": "Nie mogłem znaleźć tego raportu",
  "MarkedAsHandledButNotInDatabase": "Ten raport został oznaczony jako obsłużony na Discordzie, ale nie w bazie danych!",
  "ReportMarkedAsHandled": "Ten raport został oznaczony jako {zielony} obsłużony!",
  "CustomReason": "Wpisz powód raportu",
  "Embed.Title": "Report",
  "Embed.Player": "Player",
  "Embed.PlayerName": "Name",
  "Embed.PlayerSteamid": "SteamID",
  "Embed.Suspect": "Suspect",
  "Embed.SuspectName": "Name",
  "Embed.SuspectSteamid": "SteamID",
  "Embed.Admin": "Admin",
  "Embed.AdminName": "Name",
  "Embed.AdminSteamid": "SteamID",
  "Embed.Reason": "Reason",
  "Embed.Ip": "Ip",
  "Embed.Map": "Map",
  "Embed.Content": "**!{0} {1}** w grze, aby oznaczyć to zgłoszenie jako obsłużone. -> Możesz wpisać tutaj cokolwiek lub pozostawić puste. Pinguj członka w ten sposób: <@MemberId> lub rolę: <@&RoleId>",
  "ChatMenu.ReasonsTitle": "[{green}REPORT{default}] Wybierz powód",
  "ChatMenu.PlayersTitle": "[{green}REPORT{default}] Wybierz gracza"
}
```

**Comment by rcon420** [comment]
> ```
> {
>   "Prefix": "[{green}CallAdmin{default}]",
>   "MissingCommandPermission": "{red}Nie masz uprawnień do użycia tego polecenia!",
>   "NoPlayersAvailable": "Nie ma dostępnych graczy",
>   "InCoolDown": "Trwa czas odnowienia... poczekaj {0} sekund i spróbuj ponownie",
>   "ReportSent": "Twój raport został wysłany do administratorów!",
>   "WebhookError": "Wystąpił błąd podczas wysyłania webhooka",
>   "InsertIntoDatabaseError": "Wystąpił błąd podczas wstawiania do bazy danych!",
>   "ReportNotFound": "Nie mogłem znaleźć tego raportu",
>   "MarkedAsHandledButNotInDatabase": "Ten raport został oznaczony jako obsłużony na Discordzie, ale nie w bazie danych!",
>   "ReportMarkedAsHandled": "Ten raport został oznaczony jako {zielony} obsłużony!",
>   "CustomReason": "Wpisz powód raportu",
>   "Embed.Title": "Report",
>   "Embed.Player": "Player",
>   "Embed.PlayerName": "Name",
>   "Embed.PlayerSteamid": "SteamID",
>   "Embed.Suspect": "Suspect",
>   "Embed.SuspectName": "Name",
>   "Embed.SuspectSteamid": "SteamID",
>   "Embed.Admin": "Admin",
>   "Embed.AdminName": "Name",
>   "Embed.AdminSteamid": "SteamID",
>   "Embed.Reason": "Reason",
>   "Embed.Ip": "Ip",
>   "Embed.Map": "Map",
>   "Embed.Content": "**!{0} {1}** w grze, aby oznaczyć to zgłoszenie jako obsłużone. -> Możesz wpisać tutaj cokolwiek lub pozostawić puste. Pinguj członka w ten sposób: <@MemberId> lub rolę: <@&RoleId>",
>   "ChatMenu.ReasonsTitle": "[{green}REPORT{default}] Wybierz powód",
>   "ChatMenu.PlayersTitle": "[{green}REPORT{default}] Wybierz gracza"
> }
> ```
u should  go to lang folder and press add new file -> create new file -> fork the repo -> name it pl.json --- > add ur translations ---> submit pr changes. And author will accept or deny ur changes. hope it helps issues are ment to report bugs or give suggestions.
