### ISSUE TITLE
My another plugin can't working after install CounterStrike Sharp

### ISSUE THREAD

**Issue by denrio157** [1Mack/CS2-CallAdmin#8]
Hello, can you help me why my another plugin like "CS2SCRIM" can't work after i'm install CounterStrike Sharp? 
![image](https://github.com/1Mack/CS2-CallAdmin/assets/31591836/c4e5a4d9-7557-45e2-ae95-4ca005a454cf)

**Comment by 1Mack** [comment]
@denrio157 hey, here I just give support for calladmin, you can ask for help here -> https://discord.gg/QBsuGzZ9
