### ISSUE TITLE
Players freeze and get disconnected on report sending

### ISSUE THREAD

**Issue by lostsoul6** [1Mack/CS2-CallAdmin#9]
Hi there ,

It has happened to me a couple of times . Sometimes when the player reports another player , all players in server get disconnected and they freeze . here is what I see on console :

> L 02/06/2024 - 23:56:15: "Xept<18><[U:1:902878584]><TERRORIST>" say "!report"
> "Yamite Kodasaee<0><[U:1:1013616391]><TERRORIST>" OnPreResetRound => CTMDBG, team 2  will switch 0 1382.56 
> "arshiya_13_<1><[U:1:1603298357]><TERRORIST>" OnPreResetRound => CTMDBG, team 2  will switch 0 1382.56 
> "Arthur<2><STEAM_ID_PENDING><Unassigned>" OnPreResetRound => CTMDBG, team 0  will switch 0 1382.56 
> "-erfankiller<3><[U:1:1635221811]><TERRORIST>" OnPreResetRound => CTMDBG, team 2  will switch 0 1382.56 
> "Amir Hossein<4><[U:1:1408390108]><CT>" OnPreResetRound => CTMDBG, team 3  will switch 0 1382.56 
> "BLACK SHARK<5><[U:1:1601508922]><CT>" OnPreResetRound => CTMDBG, team 3  will switch 0 1382.56 
> "ProKo<6><STEAM_ID_PENDING><Unassigned>" OnPreResetRound => CTMDBG, team 0  will switch 0 1382.56 
> "13<7><[U:1:471973812]><CT>" OnPreResetRound => CTMDBG, team 3  will switch 0 1382.56 
> "DERFER<8><[U:1:1476812567]><TERRORIST>" OnPreResetRound => CTMDBG, team 2  will switch 0 1382.56 
> "BlackDragon<9><[U:1:1620618544]><CT>" OnPreResetRound => CTMDBG, team 3  will switch 0 1382.56 
> "j90492571<10><STEAM_ID_PENDING><Unassigned>" OnPreResetRound => CTMDBG, team 0  will switch 0 1382.56 
> "Cactusman<11><[U:1:1668622747]><CT>" OnPreResetRound => CTMDBG, team 3  will switch 0 1382.56 
> "Mr. Reese<12><[U:1:932662327]><TERRORIST>" OnPreResetRound => CTMDBG, team 2  will switch 0 1382.56 
> "mohamaderfanasayesh<14><[U:1:1528025072]><CT>" OnPreResetRound => CTMDBG, team 3  will switch 0 1382.56 
> "ðŸ‚<15><STEAM_ID_PENDING><Unassigned>" OnPreResetRound => CTMDBG, team 0  will switch 0 1382.56 
> "okthen<16><STEAM_ID_PENDING><Unassigned>" OnPreResetRound => CTMDBG, team 0  will switch 0 1382.56 
> "Mr.feshar<17><[U:1:393046149]><TERRORIST>" OnPreResetRound => CTMDBG, team 2  will switch 0 1382.56 
> "Xept<18><[U:1:902878584]><TERRORIST>" OnPreResetRound => CTMDBG, team 2  will switch 0 1382.56 
> "SHAHRAM<19><STEAM_ID_PENDING><Unassigned>" OnPreResetRound => CTMDBG, team 0  will switch 0 1382.56 
> "$hÂªÃ°Â¤w<20><[U:1:1519864505]><TERRORIST>" OnPreResetRound => CTMDBG, team 2  will switch 0 1382.56 
> "oOopS<21><[U:1:1585196222]><CT>" OnPreResetRound => CTMDBG, team 3  will switch 0 1382.56 
> L 02/06/2024 - 23:56:17: Starting Freeze period
> L 02/06/2024 - 23:56:17: "-erfankiller<3><[U:1:1635221811]><TERRORIST>" triggered "Got_The_Bomb"
> L 02/06/2024 - 23:56:17: MatchStatus: Team "CT" is unset.
> L 02/06/2024 - 23:56:17: MatchStatus: Team "TERRORIST" is unset.
> L 02/06/2024 - 23:56:17: MatchStatus: Score: 5:9 on map "de_dust2" RoundsPlayed: 14
> SV: 'Yamite Kodasaee' (tick 88490) CQ:  catching up - trying to trim queue containing 4 commands
> SV: 'arshiya_13_' (tick 88490) CQ:  catching up - trying to trim queue containing 8 commands
> SV: '-erfankiller' (tick 88490) CQ:  catching up - trying to trim queue containing 8 commands
> SV: 'Amir Hossein' (tick 88490) CQ:  catching up - trying to trim queue containing 8 commands
> SV: 'BLACK SHARK' (tick 88490) CQ:  catching up - trying to trim queue containing 5 commands
> SV: '13' (tick 88490) CQ:  catching up - trying to trim queue containing 4 commands
> SV: 'DERFER' (tick 88490) CQ:  catching up - trying to trim queue containing 5 commands
> SV: 'BlackDragon' (tick 88490) CQ:  catching up - trying to trim queue containing 6 commands
> SV: 'Cactusman' (tick 88490) CQ:  catching up - trying to trim queue containing 8 commands
> SV: 'Mr. Reese' (tick 88490) CQ:  catching up - trying to trim queue containing 6 commands
> SV: 'mohamaderfanasayesh' (tick 88490) CQ:  catching up - trying to trim queue containing 6 commands
> SV: 'Mr.feshar' (tick 88490) CQ:  catching up - trying to trim queue containing 4 commands
> SV: 'Xept' (tick 88490) CQ:  catching up - trying to trim queue containing 11 commands
> SV: '$hÂªÃ°Â¤w' (tick 88490) CQ:  catching up - trying to trim queue containing 5 commands
> SV: 'oOopS' (tick 88490) CQ:  catching up - trying to trim queue containing 9 commands
> SV: 'Yamite Kodasaee' (tick 88494) CQ:  catching up - trying to trim queue containing 1 commands
> SV: 'arshiya_13_' (tick 88494) CQ:  catching up - trying to trim queue containing 4 commands
> SV: '-erfankiller' (tick 88494) CQ:  catching up - trying to trim queue containing 4 commands
> SV: 'Amir Hossein' (tick 88494) CQ:  catching up - trying to trim queue containing 5 commands
> SV: 'BLACK SHARK' (tick 88494) CQ:  catching up - trying to trim queue containing 3 commands
> SV: '13' (tick 88494) CQ:  catching up - trying to trim queue containing 0 commands
> SV: 'DERFER' (tick 88494) CQ:  catching up - trying to trim queue containing 4 commands
> SV: 'BlackDragon' (tick 88494) CQ:  catching up - trying to trim queue containing 3 commands
> SV: 'Cactusman' (tick 88494) CQ:  catching up - trying to trim queue containing 1 commands
> SV: 'Mr. Reese' (tick 88494) CQ:  catching up - trying to trim queue containing 4 commands
> SV: 'mohamaderfanasayesh' (tick 88494) CQ:  catching up - trying to trim queue containing 1 commands
> SV: 'Mr.feshar' (tick 88494) CQ:  catching up - trying to trim queue containing 1 commands
> SV: 'Xept' (tick 88494) CQ:  catching up - trying to trim queue containing 4 commands
> SV: '$hÂªÃ°Â¤w' (tick 88494) CQ:  catching up - trying to trim queue containing 3 commands
> SV: 'oOopS' (tick 88494) CQ:  catching up - trying to trim queue containing 4 commands
> SV: 'arshiya_13_' (tick 88496) CQ:  catching up - trying to trim queue containing 1 commands
> SV: '-erfankiller' (tick 88496) CQ:  catching up - trying to trim queue containing 1 commands
> SV: 'Amir Hossein' (tick 88496) CQ:  catching up - trying to trim queue containing 1 commands
> SV: 'BLACK SHARK' (tick 88496) CQ:  catching up - trying to trim queue containing 1 commands
> SV: 'DERFER' (tick 88496) CQ:  catching up - trying to trim queue containing 1 commands
> SV: 'BlackDragon' (tick 88496) CQ:  catching up - trying to trim queue containing 1 commands
> SV: 'Mr. Reese' (tick 88496) CQ:  catching up - trying to trim queue containing 1 commands
> SV: 'Xept' (tick 88496) CQ:  catching up - trying to trim queue containing 1 commands
> SV: '$hÂªÃ°Â¤w' (tick 88496) CQ:  catching up - trying to trim queue containing 1 commands
> SV: 'oOopS' (tick 88496) CQ:  catching up - trying to trim queue containing 5 commands
> SV: 'oOopS' (tick 88498) CQ:  catching up - trying to trim queue containing 4 commands
> SV: 'oOopS' (tick 88499) CQ:  catching up - trying to trim queue containing 4 commands
> SV: 'oOopS' (tick 88500) CQ:  catching up - trying to trim queue containing 4 commands
> SV: 'oOopS' (tick 88501) CQ:  catching up - trying to trim queue containing 4 commands
> SV: 'oOopS' (tick 88502) CQ:  catching up - trying to trim queue containing 4 commands
> SV: 'oOopS' (tick 88503) CQ:  catching up - trying to trim queue containing 4 commands
> SV: 'oOopS' (tick 88504) CQ:  catching up - trying to trim queue containing 1 commands
> L 02/06/2024 - 23:56:18: "Yamite Kodasaee<0><[U:1:1013616391]><TERRORIST>" purchased "ak47"
> L 02/06/2024 - 23:56:18: "Yamite Kodasaee<0><[U:1:1013616391]><TERRORIST>" purchased "smokegrenade"
> L 02/06/2024 - 23:56:19: "-erfankiller<3><[U:1:1635221811]><TERRORIST>" purchased "molotov"
> L 02/06/2024 - 23:56:19: "Yamite Kodasaee<0><[U:1:1013616391]><TERRORIST>" purchased "flashbang"
> L 02/06/2024 - 23:56:19: "13<7><[U:1:471973812]><CT>" purchased "m4a1_silencer"
> L 02/06/2024 - 23:56:19: "-erfankiller<3><[U:1:1635221811]><TERRORIST>" purchased "hegrenade"
> L 02/06/2024 - 23:56:19: "Yamite Kodasaee<0><[U:1:1013616391]><TERRORIST>" purchased "flashbang"
> L 02/06/2024 - 23:56:19: "Cactusman<11><[U:1:1668622747]><CT>" purchased "ssg08"
> L 02/06/2024 - 23:56:19: "-erfankiller<3><[U:1:1635221811]><TERRORIST>" purchased "smokegrenade"
> [All Chat][Xept (902878584)]: !7
> L 02/06/2024 - 23:56:19: "Xept<18><[U:1:902878584]><TERRORIST>" say "!7"
> L 02/06/2024 - 23:56:19: "Mr.feshar<17><[U:1:393046149]><TERRORIST>" purchased "ak47"
> L 02/06/2024 - 23:56:19: "BlackDragon<9><[U:1:1620618544]><CT>" purchased "bizon"
> L 02/06/2024 - 23:56:19: "DERFER<8><[U:1:1476812567]><TERRORIST>" purchased "hegrenade"
> L 02/06/2024 - 23:56:20: "Cactusman<11><[U:1:1668622747]><CT>" purchased "deagle"
> L 02/06/2024 - 23:56:20: "oOopS<21><[U:1:1585196222]><CT>" purchased "nova"
> L 02/06/2024 - 23:56:20: "mohamaderfanasayesh<14><[U:1:1528025072]><CT>" purchased "ssg08"
> L 02/06/2024 - 23:56:20: "$hÂªÃ°Â¤w<20><[U:1:1519864505]><TERRORIST>" purchased "ak47"
> RemoveArrayElementsOutsideOfArrayMetadataBounds:  CCSGOViewModel [ent 84] removing change '3/7/45' for field m_PredNetByteVariables[45] (value '0') on array that has metadata with only 43 array elements!
> L 02/06/2024 - 23:56:20: "DERFER<8><[U:1:1476812567]><TERRORIST>" purchased "molotov"
> L 02/06/2024 - 23:56:20: "Cactusman<11><[U:1:1668622747]><CT>" purchased "hegrenade"
> L 02/06/2024 - 23:56:20: "BlackDragon<9><[U:1:1620618544]><CT>" purchased "smokegrenade"
> [All Chat][BLACK SHARK (1601508922)]: !report
> L 02/06/2024 - 23:56:20: "BLACK SHARK<5><[U:1:1601508922]><CT>" say "!report"
> L 02/06/2024 - 23:56:20: "DERFER<8><[U:1:1476812567]><TERRORIST>" purchased "smokegrenade"
> L 02/06/2024 - 23:56:20: "Mr. Reese<12><[U:1:932662327]><TERRORIST>" purchased "ak47"
> L 02/06/2024 - 23:56:21: "BlackDragon<9><[U:1:1620618544]><CT>" purchased "incgrenade"
> L 02/06/2024 - 23:56:21: "mohamaderfanasayesh<14><[U:1:1528025072]><CT>" purchased "incgrenade"
> L 02/06/2024 - 23:56:22: "BlackDragon<9><[U:1:1620618544]><CT>" purchased "decoy"
> RemoveArrayElementsOutsideOfArrayMetadataBounds:  CCSGOViewModel [ent 74] removing change '3/9/39' for field m_PredNetIntVariables[39] (value '0') on array that has metadata with only 39 array elements!
> L 02/06/2024 - 23:56:22: World triggered "Round_Start"
> L 02/06/2024 - 23:56:22: "$hÂªÃ°Â¤w<20><[U:1:1519864505]><TERRORIST>" purchased "flashbang"
> L 02/06/2024 - 23:56:22: "arshiya_13_<1><[U:1:1603298357]><TERRORIST>" purchased "molotov"
> L 02/06/2024 - 23:56:22: "Amir Hossein<4><[U:1:1408390108]><CT>" purchased "deagle"
> L 02/06/2024 - 23:56:22: "arshiya_13_<1><[U:1:1603298357]><TERRORIST>" purchased "smokegrenade"
> L 02/06/2024 - 23:56:22: "Amir Hossein<4><[U:1:1408390108]><CT>" purchased "smokegrenade"
> L 02/06/2024 - 23:56:23: "Amir Hossein<4><[U:1:1408390108]><CT>" purchased "incgrenade"
> RemoveArrayElementsOutsideOfArrayMetadataBounds:  CCSGOViewModel [ent 307] removing change '3/7/57' for field m_PredNetByteVariables[57] (value '0') on array that has metadata with only 57 array elements!
> sv: Firing first shot, sv tick 88895, but no attack information present in command 88445 with 2 history entries
>     command tick: 88887
>     attack1_start_history_index: -1
>     attack2_start_history_index: -1
>     attack3_start_history_index: -1
>     history: 88893.976562
>     history: 88895.445312
> [All Chat][Xept (902878584)]: !1
> L 02/06/2024 - 23:56:24: "Xept<18><[U:1:902878584]><TERRORIST>" say "!1"
> RemoveArrayElementsOutsideOfArrayMetadataBounds:  CCSGOViewModel [ent 74] removing change '3/7/55' for field m_PredNetByteVariables[55] (value '0') on array that has metadata with only 54 array elements!
> L 02/06/2024 - 23:56:27: "Xept<18><[U:1:902878584]><TERRORIST>" purchased "ak47"
> L 02/06/2024 - 23:56:28: "Mr. Reese<12><[U:1:932662327]><TERRORIST>" [-533 -754 114] committed suicide with "world"
> [#229178057 UDP steamid:76561199437078295@5.122.125.208:15552] closed by peer (1002): NETWORK_DISCONNECT_DISCONNECT_BY_USER
> [#1860533379 UDP steamid:76561198353311877@217.219.239.193:56332] recv queue overflow 1000 messages already queued.
> [#1860533379 UDP steamid:76561198353311877@217.219.239.193:56332] recv queue overflow 1000 messages already queued.
> [#1860533379 UDP steamid:76561198353311877@217.219.239.193:56332] recv queue overflow 1000 messages already queued.
> [#1714101418 UDP steamid:76561199368655836@86.55.241.30:54354] recv queue overflow 1000 messages already queued.
> [#1849244482 UDP steamid:76561199480130233@178.131.145.166:57418] recv queue overflow 1000 messages already queued.
> [#2178530656 UDP steamid:76561198973882119@185.125.252.13:55583] recv queue overflow 1000 messages already queued.
> [#547935658 UDP steamid:76561199580884272@5.112.111.39:34233] recv queue overflow 1000 messages already queued.
> [#547935658 UDP steamid:76561199580884272@5.112.111.39:34233] recv queue overflow 1000 messages already queued.
> [#1849244482 UDP steamid:76561199480130233@178.131.145.166:57418] recv queue overflow 1000 messages already queued.
> [#3267309751 UDP steamid:76561199563564085@5.219.227.98:59324] recv queue overflow 1000 messages already queued.
> [#1010165046 UDP steamid:76561199561774650@2.185.11.131:28251] recv queue overflow 1000 messages already queued.
> [#364707844 UDP steamid:76561198432239540@2.176.11.163:41069] recv queue overflow 1000 messages already queued.
> [#229178057 UDP steamid:76561199437078295@5.122.125.208:15552] We are in state 4 and have been waiting 20.0s to be cleaned up.  Did you forget to call CloseConnection()?
> [#2178530656 UDP steamid:76561198973882119@185.125.252.13:55583] closed by peer (2999): NETWORK_DISCONNECT_DISCONNECT_BY_USER
> [#2356706960 UDP steamid:76561198892928055@31.57.21.143:55081] recv queue overflow 1000 messages already queued.
> [#2356706960 UDP steamid:76561198892928055@31.57.21.143:55081] recv queue overflow 1000 messages already queued.
> [#2356706960 UDP steamid:76561198892928055@31.57.21.143:55081] recv queue overflow 1000 messages already queued.
> [#547935658 UDP steamid:76561199580884272@5.112.111.39:34233] closed by peer (2055): NETWORK_DISCONNECT_LOOPDEACTIVATE
[#2120614406 UDP steamid:76561198892928055@31.57.21.143:51198] We are in state 4 and have been waiting 20.0s to be cleaned up.  Did you forget to call CloseConnection()?
[#101839950 UDP steamid:76561199031428508@31.7.99.18:12783] We are in state 4 and have been waiting 20.0s to be cleaned up.  Did you forget to call CloseConnection()?
[#4160970966 UDP steamid:76561198361783643@5.213.203.112:51751] recv queue overflow 1000 messages already queued.
[#4134306248 UDP steamid:76561198997467815@46.143.52.120:52125] recv queue overflow 1000 messages already queued.
[#4134306248 UDP steamid:76561198997467815@46.143.52.120:52125] recv queue overflow 1000 messages already queued.
[#736893429 UDP steamid:76561198361783643@5.213.203.112:62724] closed by peer (5003): Timed out attempting to connect
[#2830158729 UDP steamid:76561199563381959@46.143.73.240:56883] closed by peer (5003): Timed out attempting to connect
[#1912345603 UDP steamid:76561199574936927@2.187.122.232:52438] closed by peer (1000): CloseSocket
[#4160970966 UDP steamid:76561198361783643@5.213.203.112:51751] recv queue overflow 1000 messages already queued.
[#4160970966 UDP steamid:76561198361783643@5.213.203.112:51751] recv queue overflow 1000 messages already queued.
[#4160970966 UDP steamid:76561198361783643@5.213.203.112:51751] recv queue overflow 1000 messages already queued.
[#2241707474 UDP steamid:76561199563381959@46.143.73.240:58983] recv queue overflow 1000 messages already queued.
[#4160970966 UDP steamid:76561198361783643@5.213.203.112:51751] recv queue overflow 1000 messages already queued.
[#4134306248 UDP steamid:76561198997467815@46.143.52.120:52125] recv queue overflow 1000 messages already queued.
[#3306014004 UDP steamid:76561199563136898@86.57.40.153:58566] closed by peer (5003): Timed out attempting to connect
[#3181023920 UDP steamid:76561199031428508@31.7.99.18:12961] closed by peer (1000): CloseSocket
WatchDog! Server took too long to process (probably infinite loop)
Watchdog timeout exceeded, exiting
 0 Watchdog timeout exceeded, exiting

Has anyone reported such issue before ? As I see players Xept and BLACK SHARK both started !report . Could this be the issue? What happens if the report can't be sent ? Will it end the process with failed message or it keeps trying?

**Comment by 1Mack** [comment]
Im fixing it. 
If the report can't be sent, the plugin will throw a warning

**Comment by 1Mack** [comment]
https://github.com/1Mack/CS2-CallAdmin/releases/tag/V1.1.0
